### ISSUE TITLE
Upgrade to HA 2023.4.5 causing exception

### ISSUE THREAD

**Issue by klasenby** [b0mbays/continuously_casting_dashboards#10]
I just updated to HA 2023.4.5 and now get a Python exception in continuously_casting_dashboard, dashboards are not displayed.

I'm using the homeassistant docker image (https://registry.hub.docker.com/r/homeassistant/home-assistant/). I have tried restarting the container and HA a few times, same error every time.

Here is the error (debug logging is enabled).

--------------------

2023-04-18 20:28:55.279 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/subprocess.py", line 195, in communicate
    stdin, stdout, stderr = await tasks.gather(stdin, stdout, stderr)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/continuously_casting_dashboards/dashboard_caster.py", line 240, in start
    if (await self.check_both_states(device_name)) is None:
  File "/config/custom_components/continuously_casting_dashboards/dashboard_caster.py", line 173, in check_both_states
    status_output = await self.check_status(device_name, dashboard_state_name)
  File "/config/custom_components/continuously_casting_dashboards/dashboard_caster.py", line 115, in check_status
    stdout, stderr = await asyncio.wait_for(process.communicate(), timeout=10)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

**Comment by b0mbays** [comment]
Hey @klasenby , I am updating to HA - 2023.4.5 now and i'll let you know if I have any issues 👍

**Comment by b0mbays** [comment]
I have updated to both HA OS 10.0 and HA Core 2023.4.5 and the integration is working as it was before. Succesfully casting to 5 displays. Could you post your configuration setup for the integration?

**Comment by b0mbays** [comment]
Are you still having the same problem @klasenby ?

**Comment by klasenby** [comment]
I am, and haven't had a chance to look into it further yet. My guess is, some component got upgraded in the docker container.

**Comment by dominickdm** [comment]
After the installation (first time), I had the same exception error messages in my log file.
After a reboot of the system (rpi in my case), it worked fine.

**Comment by klasenby** [comment]
Just updated to 2023.4.6 and now everything works again!

**Comment by b0mbays** [comment]
Well, that's good to hear 😁
