### ISSUE TITLE
Cast on demand

### ISSUE THREAD

**Issue by donparlor** [b0mbays/continuously_casting_dashboards#33]
Hello [@b0mbays](https://community.home-assistant.io/u/b0mbays),

Wonderful work with this HACS. I went through the setup process easily but I am wondering if instead of casting through a defined timeframe I could simply cast on demand. I mean, I want to cast a specific dashboard in my garage TV with a Chromecast (Google TV) on request for a project and time will vary depending on when I start the project and how fast the project is completed. Based on your configuration it seems we must set a defined start and end time or it will default to 7:00 AM.

continuously_casting_dashboards:
  logging_level: warning #Required: Set the logging level - debug/info/warning (default is 'warning' - try 'debug' for debugging)
  cast_delay: 45 #Required: Time (in seconds) for casting checks between each device.
  start_time: "07:00" #Optional: Global start time of the casting window (format: "HH:MM") - Default is set to "07:00" and can be individually overwritten per device below.
  end_time: "01:00" #Optional: Global end time of the casting window (format: "HH:MM") and must be after "00:00". Default is set to "01:00" and can be individually overwritten per device below.
  devices:
    "<Display_Name>": #Required: Display name of your device. Find this on the actual device's settings or inside the Google Home app.
        dashboard_url: "<Dashboard_URL>" #Required: Dashboard URL to be casted (This must be the local IP address of your HA instance, not homeassistant.local)
        volume: 5 #Optional: Volume to set the display. (If you remove this, the device will remain the same volume)
        start_time: "07:00" #Optional: Set the start time for this device
        end_time: "01:00" #Optional: Set the end time for this device
Before discovering your HACS, I had created a button in my garage dashboard to cast on my Garage Google TV, but it would stop after 10min and go into Photo Mode. The only way to go back to displaying my dashboard is to click the BACK button on the physical remote of the Google TV,

Here is my button code:

type: custom:button-card
name: Caster Distillation
icon: mdi:cast
tap_action:
  action: call-service
  service: script.1692141275657
hold_action:
  action: call-service
  service: media_player.turn_off
  service_data:
    entity_id: media_player.google_tv_garage
show_name: true
show_icon: true
And here is the script it is referring to:

alias: Cast Garage
sequence:
  - service: media_player.turn_on
    target:
      entity_id:
        - media_player.google_tv_garage
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: cast.show_lovelace_view
    data:
      entity_id: media_player.google_tv_garage
      dashboard_path: lovelace
      view_path: distillation
mode: single
Any idea if your HACS could work based on time when it is required to cast?

**Comment by b0mbays** [comment]
Hey @donparlor thanks for the kind words. You could try using the [_Entity based dashboard casting feature_ ](https://github.com/b0mbays/continuously_casting_dashboards#-entity-changed-dashboard-casting) to cast your dashboard when an entity changes? This entity could be the same button you used previously or something else that you want to use as your 'on demand switch'.

I created a 'dummy' switch to replicate the state of my TV being 'turned on' and it will cast the dashboard when I set this switch to 'on'

![Screenshot 2023-08-21 at 11 04 31](https://github.com/b0mbays/continuously_casting_dashboards/assets/55556007/3d588a3d-c2fc-4afe-835a-fb74951be349)

**Comment by donparlor** [comment]
Brilliant! Yes you are correct, I can easily have a boolean to trigger the casting. I'll try it and it should be good to go! Thanks!

**Comment by donparlor** [comment]
If I use the entity based trigger, do I need to configure the basic configuration described here?
![Capture d’écran, le 2023-08-21 à 10 56 42](https://github.com/b0mbays/continuously_casting_dashboards/assets/97048708/a74cfe51-5ec9-4f95-9ff9-ca0fe74ce6fb)

I would guess not...

And I guess only that portion needs to be configured:
![Capture d’écran, le 2023-08-21 à 10 56 48](https://github.com/b0mbays/continuously_casting_dashboards/assets/97048708/70a6cbe0-8b52-4813-b0ca-392cfb648210)

**Comment by b0mbays** [comment]
Good question... I'm actually not sure. It could be required. Could you try it with and without? I'm not at home right now to test it unfortunately

**Comment by donparlor** [comment]
Ok I will

**Comment by donparlor** [comment]
Cette erreur provient d'une intégration personnalisée

Logger: homeassistant.setup
Source: custom_components/continuously_casting_dashboards/dashboard_caster.py:16
Integration: continuously_casting_dashboards
First occurred: 16:36:58 (1 occurrences)
Last logged: 16:36:58

Error during setup of component continuously_casting_dashboards
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/continuously_casting_dashboards/__init__.py", line 20, in async_setup
    caster = ContinuouslyCastingDashboards(hass, conf)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/continuously_casting_dashboards/dashboard_caster.py", line 16, in __init__
    self.cast_delay = self.config['cast_delay']
                      ~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'cast_delay'

**Comment by donparlor** [comment]
Here is my configuration.yaml
![Capture d’écran, le 2023-08-21 à 16 56 57](https://github.com/b0mbays/continuously_casting_dashboards/assets/97048708/d258764c-a161-4777-a14d-3d843bb00924)

**Comment by donparlor** [comment]
I did try the same with an external HTTPS url using my own domain with Cloudflare.

**Comment by donparlor** [comment]
Is it possible that there is missing a  'cast_delay' value? 

Referring to: KeyError: 'cast_delay'
![Capture d’écran, le 2023-08-21 à 21 00 32](https://github.com/b0mbays/continuously_casting_dashboards/assets/97048708/78018b59-0bef-4d28-8e47-cfa28eae3435)

**Comment by donparlor** [comment]
I got it, logging_level and cast_delay are #Required in your configuration.

**Comment by b0mbays** [comment]
Glad you sorted it out! Does that new trigger work well for you?

**Comment by donparlor** [comment]
Have a look, the HACS does not work. It tries to display the local URL which work from my computer but it goes into a loop on the Google TV Screen.

https://github.com/b0mbays/continuously_casting_dashboards/assets/97048708/8345500b-a4c8-476a-9d0f-8625ab955fa6

**Comment by donparlor** [comment]
And for your information, my dashboard URL is working in my browser
<img width="1364" alt="Capture d’écran, le 2023-08-22 à 11 02 50" src="https://github.com/b0mbays/continuously_casting_dashboards/assets/97048708/f38cb2aa-fefd-4391-845a-9bb8ad7961a0">

**Comment by b0mbays** [comment]
Hey @donparlor - apologies I have been away. I've assumed that this integration works with Chromecast devices on TV's but that doesn't seem to be the case after doing a test with mine. It looks like this only works with Google Display Hub devices unfortunately 😞

**Comment by donparlor** [comment]
Since your HACS is based on CATT's created by @skorokithakis, could skorokithakis take into account the Google TV requirements for CATT to work with it?

**Comment by donparlor** [comment]
@b0mbays, here is skorokithakis's answer, creator of the CATT component

<img width="932" alt="Capture d’écran, le 2023-09-04 à 10 03 23" src="https://github.com/b0mbays/continuously_casting_dashboards/assets/97048708/07700a83-08f3-46bf-b5de-3f563d2284cb">

**Comment by Tokn59** [comment]
Did anyone finally get the triggers working ? Can you please poost your FULL working yaml for CCD ? Thank You !!!
