### ISSUE TITLE
Error during setup of component continuously_casting_dashboards

### ISSUE THREAD

**Issue by thewookiewon** [b0mbays/continuously_casting_dashboards#72]
Started getting this error, unknown what triggered it but it's stopped casting to my device. Restarts of HA doesn't resolve it. 

Logger: homeassistant.setup
Source: setup.py:404
First occurred: 18:48:25 (1 occurrences)
Last logged: 18:48:25

Error during setup of component continuously_casting_dashboards
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 404, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/continuously_casting_dashboards/__init__.py", line 20, in async_setup
    caster = ContinuouslyCastingDashboards(hass, conf)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/continuously_casting_dashboards/dashboard_caster.py", line 31, in __init__
    for dashid, device_info in enumerate(d_info):
                               ^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not iterable

**Comment by thewookiewon** [comment]
Turned out it's was a stupid missing line indent, I moved the code from configuration.yaml to its own yaml file then included that in the config file
