### ISSUE TITLE
Logger "homeassistant": Error doing job: Task exception was never retrieved (None)

### ISSUE THREAD

**Issue by MickLesk** [b0mbays/continuously_casting_dashboards#76]
I get this error quite often in the log. Unfortunately, I don't know why. I have already had a rough look at the location, but could not see any direct error.

```yaml
# Google Nest Hub Integration
continuously_casting_dashboards:
  logging_level: warning 
  cast_delay: 3600 
  start_time: "07:00" 
  end_time: "22:00" 
  devices:
    "Nest Hub": 
      - dashboard_url: "http://192.***.**.***:****/dashboard-google/google?kiosk" #Required: Dashboard URL to be casted (This must be the local IP address of your HA instance, not homeassistant.local)
        volume: 5 
        start_time: "07:00" 
        end_time: "23:00" 
  state_triggers:
    "Push 1":
      - entity_id: "media_player.nest_hub"
        to_state: "idle"
        dashboard_url: "http://192.***.**.***:****/dashboard-google/google?kiosk"
        time_out: 60
        force_cast: true
shell_command:
  cast_weather: catt -d "Nest Hub" cast_site http://192.***.**.***:****/dashboard-google/google?kiosk
```

```python
Logger: homeassistant
Source: custom_components/continuously_casting_dashboards/dashboard_caster.py:229
Integration: Continuously Cast Dashboards (documentation)
First occurrence: 09:13:55 (16 occurrences)
Last logged: 11:22:41

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/continuously_casting_dashboards/dashboard_caster.py", line 125, in handle_state_change_event
    media_playing = await self.check_media_state(device_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/continuously_casting_dashboards/dashboard_caster.py", line 229, in check_media_state
    media_state_name = self.device_map[device_name]["media_state_name"]
                       ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'Push 1'
```

**Comment by ENT108** [comment]
Same here

**Comment by Jimfizz** [comment]
I have the same issue... I tried 2 different cast devices and encountered the error on twice

**Comment by b0mbays** [comment]
This issue should be resolved in the latest version. I'll re-open if you experience it again 👍
