### ISSUE TITLE
OSError: [Errno 105] No buffer space available when running 'catt'

### ISSUE THREAD

**Issue by joelis10** [b0mbays/continuously_casting_dashboards#80]
Yesterday, my HA stopped casting to my 3 displays that I currently had dashboards displaying on. I tried restarting the container and server itself multiple times, but no matter what I do, I can't get them back. I tried manually running `catt` inside the container, but giving the command any arguments spits back a long Python error:
```
Traceback (most recent call last):
  File "/usr/local/bin/catt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/catt/cli.py", line 667, in main
    return cli(obj=get_config_as_dict())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/catt/cli.py", line 320, in cast_site
    cst = setup_cast(
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/catt/controllers.py", line 78, in setup_cast
    cast = get_cast(device_desc)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/catt/discovery.py", line 117, in get_cast
    cast = get_cast_with_name(cast_desc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/catt/discovery.py", line 61, in get_cast_with_name
    casts = get_casts([cast_name]) if cast_name else get_casts()
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/catt/discovery.py", line 25, in get_casts
    cast_infos, browser = pychromecast.discovery.discover_listed_chromecasts(friendly_names=names)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pychromecast/discovery.py", line 704, in discover_listed_chromecasts
    zconf = zeroconf_instance or zeroconf.Zeroconf()
                                 ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zeroconf/_core.py", line 179, in __init__
    listen_socket, respond_sockets = create_sockets(interfaces, unicast, ip_version, apple_p2p=apple_p2p)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zeroconf/_utils/net.py", line 383, in create_sockets
    if add_multicast_member(cast(socket.socket, listen_socket), i):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zeroconf/_utils/net.py", line 293, in add_multicast_member
    listen_socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, _value)
OSError: [Errno 105] No buffer space available
```

I've looked all over the place and tried reinstalling and downgrading `catt` but nothing has worked so far.
edit: wanted to confirm that 'no buffer space available' is definitely the issue - I see it happening in the HA logs in the container too

**Comment by joelis10** [comment]
For anyone else with this issue, I found a fix! I found [this issue for CATT](https://github.com/skorokithakis/catt/issues/328) (the cast thing that this integration uses) and followed the steps in the last comment above mine.
