### ISSUE TITLE
Invalid config

### ISSUE THREAD

**Issue by Tokn59** [b0mbays/continuously_casting_dashboards#84]
Hi, since one of the last updates of HA (2024.x) I get this integration error :

'Logger: homeassistant.setup
Source: setup.py:334
First occurred: 4 November 2024 at 17:37:29 (1 occurrences)
Last logged: 4 November 2024 at 17:37:29

Setup failed for 'cast': Unable to import component: No module named 'pychromecast'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/src/homeassistant/homeassistant/components/cast/__init__.py", line 7, in <module>
    from pychromecast import Chromecast
ModuleNotFoundError: No module named 'pychromecast'

**My config :** 

'#-----------------------------------------------------------------------------------------------------
continuously_casting_dashboards:
  logging_level: debug #Required: Set the logging level - debug/info/warning (default is 'warning' - try 'debug' for debugging)
  cast_delay: 15
  start_time: "00:01" #Required: Start time of the casting window (format: "HH:MM")
  end_time: "23:59" #Required: End time of the casting window (format: "HH:MM") and must be after "00:00"
  #  volume: 5 #
  #  devices:
  #    "Nesthub Kitchen":
  #      dashboard_url: "http://192.168.1.15:8443/tablet-2/default_view?kiosk"
  #      volume: <Volume>
  #      start_time: "07:01" #Required: Start time of the casting window (format: "HH:MM")
  #      end_time: "22:30" #Required: End time of the casting window (format: "HH:MM") and must be after "00:00"
  devices:
    "Kitchen Display":
      #      - entity_id: input_boolean.nesthub_alarm
      #        to_state: "on"
      #        dashboard_url: "http://192.168.1.15:8443/dashboard-cameras/default_view?kiosk"
      #        volume: 5
      #      - entity_id: input_boolean.nesthub_alarm
      #        to_state: "off"
      dashboard_url: "http://192.168.1.15:8443/dashboard-nesthub/default_view?kiosk"
      volume: 1
    "Desk Display":
      #      - entity_id: input_boolean.nesthub_alarm
      #        to_state: "on"
      #      dashboard_url: "http://192.168.1.15:8443/dashboard-cameras/default_view?kiosk"
      dashboard_url: "http://192.168.1.15:8443/dashboard-nesthub/default_view?kiosk"
      #        volume: 5
      #      - entity_id: input_boolean.nesthub_alarm
      #        to_state: "off"
      #        dashboard_url: "http://192.168.1.15:8443/dashboard-cameras/default_view?kiosk""
      volume: 1
#-----------------------------------------------------------------------------------------------------

Any idea what is wrong here and how to solve it ?

THANKS !!!!

**Comment by b0mbays** [comment]
Are you still having issues with this?

**Comment by b0mbays** [comment]
The latest version should be more stable. Update and let me know 👍

**Comment by Tokn59** [comment]
I currently have version 1.2.6 .... I see not "request" for update in HACS ?

**Comment by b0mbays** [comment]
Update the information for the integration, then click redownload 👍

**Comment by Tokn59** [comment]
I upgraded to version 2.0.0 and then to version 2.0.1
The displays do no longer receive anything. I activated debug logging. When consulting the system log : 

<img width="1149" alt="Image" src="https://github.com/user-attachments/assets/e91adcfa-673f-4586-90a1-c01575577185" />

**Comment by b0mbays** [comment]
Could you post your full configuration formatted correctly in here? Could you try switching from using the name of the device to the direct IP?

Like this:

```
continuously_casting_dashboards:
  logging_level: warning 
  cast_delay: 45 
  start_time: "07:00"
  end_time: "01:00"
  devices:
    "192.168.1.37":
      - dashboard_url: "<Dashboard_URL>"
        volume: 5 #
        start_time: "07:00" 
        end_time: "01:00"
```

**Comment by Tokn59** [comment]
Sure ! Here is my config (did not change it between versions". So this is from te working version:

`#-----------------------------------------------------------------------------------------------------
continuously_casting_dashboards:
  logging_level: debug #Required: Set the logging level - debug/info/warning (default is 'warning' - try 'debug' for debugging)
  cast_delay: 45
  start_time: "00:01" #Required: Start time of the casting window (format: "HH:MM")
  end_time: "23:59" #Required: End time of the casting window (format: "HH:MM") and must be after "00:00"
  devices:
    "Desk Display":
      dashboard_url: "http://192.168.1.15:8443/dashboard-kiosk/0?kiosk"
      volume: 1
    "Kitchen Display":
      #      dashboard_url: "http://192.168.1.15:8443/dashboard-nesthub/default_view?kiosk"
      dashboard_url: "http://192.168.1.15:8443/dashboard-kiosk/0?kiosk"
      volume: 1
#-----------------------------------------------------------------------------------------------------
`

**Comment by Tokn59** [comment]
I will first have to restore the latest version of HA from my backup so I will wait until you validate my config top do so.

**Comment by b0mbays** [comment]
It looks like you may have been quite a few versions behind before (1.2.6) - I had to add a document for a change you need to make when updating to 1.3.0 which is why your casting has stopped

Here is the doc that will fix your issue 👍 

https://github.com/b0mbays/continuously_casting_dashboards/blob/main/docs/update-help-1.3.0.md
